# Generated by Django 4.2 on 2026-01-12 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InstructionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('condition_text', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='InstructionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('is_prohibited', models.BooleanField(default=False)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Information')], max_length=20)),
                ('instruction_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='bot.instructionblock')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('threat_level', models.CharField(choices=[('immediate', 'Immediate'), ('normal', 'Normal')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sop_type', models.CharField(choices=[('immediate', 'Immediate'), ('normal', 'Normal')], max_length=20)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sop', to='bot.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='SOPConditionMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_maps', to='bot.sop')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_immediate', models.BooleanField(default=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='bot.scenario')),
            ],
        ),
        migrations.DeleteModel(
            name='EmergencyResponse',
        ),
        migrations.AddField(
            model_name='sopconditionmap',
            name='threat_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sop_maps', to='bot.threatcondition'),
        ),
        migrations.AddField(
            model_name='instructionblock',
            name='sop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='bot.sop'),
        ),
        migrations.AddField(
            model_name='conditiontrigger',
            name='threat_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='bot.threatcondition'),
        ),
        migrations.AlterUniqueTogether(
            name='sopconditionmap',
            unique_together={('sop', 'threat_condition')},
        ),
    ]
