# Generated by Django 4.2 on 2026-01-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_conditiontrigger_instructionblock_instructionstep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='site_type',
            field=models.CharField(choices=[('house', 'House'), ('building', 'Building'), ('fFactory', 'Factory'), ('warehouse', 'Warehouse'), ('greenland', 'Greenland')], max_length=50, null=True),
        ),
    ]
