# Generated by Django 4.2 on 2026-01-13 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_scenario_site_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AreaHazardMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazard_maps', to='bot.area')),
            ],
        ),
        migrations.CreateModel(
            name='HazardIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HazardLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('hazard_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='bot.hazardindicator')),
            ],
            options={
                'unique_together': {('hazard_indicator', 'level')},
            },
        ),
        migrations.CreateModel(
            name='HazardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.PositiveIntegerField()),
                ('max_score', models.PositiveIntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_rules', to='bot.area')),
                ('risk_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_rules', to='bot.risklevel')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_rules', to='bot.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sopconditionmap',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sopconditionmap',
            name='sop',
        ),
        migrations.RemoveField(
            model_name='sopconditionmap',
            name='threat_condition',
        ),
        migrations.RemoveField(
            model_name='threatcondition',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='instructionblock',
            name='condition_text',
        ),
        migrations.RemoveField(
            model_name='instructionstep',
            name='severity',
        ),
        migrations.AlterField(
            model_name='sop',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sops', to='bot.scenario'),
        ),
        migrations.DeleteModel(
            name='ConditionTrigger',
        ),
        migrations.DeleteModel(
            name='SOPConditionMap',
        ),
        migrations.DeleteModel(
            name='ThreatCondition',
        ),
        migrations.AddField(
            model_name='areahazardmap',
            name='hazard_indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_maps', to='bot.hazardindicator'),
        ),
        migrations.AddField(
            model_name='area',
            name='site_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='bot.sitetype'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='hazard_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='bot.hazardtype'),
        ),
        migrations.AddField(
            model_name='sop',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sops', to='bot.area'),
        ),
        migrations.AddField(
            model_name='sop',
            name='risk_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sops', to='bot.risklevel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scenario',
            name='site_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='bot.sitetype'),
        ),
        migrations.AlterUniqueTogether(
            name='scenario',
            unique_together={('hazard_type', 'site_type')},
        ),
        migrations.AlterUniqueTogether(
            name='sop',
            unique_together={('scenario', 'area', 'risk_level')},
        ),
        migrations.AlterUniqueTogether(
            name='areahazardmap',
            unique_together={('area', 'hazard_indicator')},
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('site_type', 'name')},
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='description',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='name',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='threat_level',
        ),
        migrations.RemoveField(
            model_name='sop',
            name='sop_type',
        ),
    ]
