# Generated by Django 4.2 on 2026-01-22 23:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_area_areahazardmap_hazardindicator_hazardlevel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name (e.g., 'house', 'building')", max_length=50, unique=True)),
                ('display_name', models.CharField(help_text="Display name (e.g., 'House Fire', 'Building Fire')", max_length=100)),
                ('icon', models.CharField(blank=True, help_text="Emoji icon (e.g., '🏠', '🏢')", max_length=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this category', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in menus')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fire Category',
                'verbose_name_plural': 'Fire Categories',
                'db_table': 'fire_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_key', models.CharField(help_text="Unique lookup key (e.g., 'house_kitchen_critical')", max_length=100, unique=True)),
                ('title', models.CharField(help_text='Response title/header', max_length=200)),
                ('content', models.TextField(help_text='Main response content')),
                ('additional_warning', models.TextField(blank=True, help_text='Additional context-specific warning', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this response is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='bot.firecategory')),
            ],
            options={
                'verbose_name': 'Fire Response',
                'verbose_name_plural': 'Fire Responses',
                'db_table': 'fire_responses',
                'ordering': ['category', 'sub_category', 'risk_level'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name (e.g., 'kitchen', 'electrical')", max_length=50)),
                ('display_name', models.CharField(help_text="Display name (e.g., 'Kitchen Fire', 'Electrical Fire')", max_length=100)),
                ('icon', models.CharField(blank=True, help_text="Emoji icon (e.g., '🍳', '⚡')", max_length=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('has_risk_levels', models.BooleanField(default=True, help_text='Whether this sub-category uses risk levels')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within category')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this sub-category is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='bot.firecategory')),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
                'db_table': 'sub_categories',
                'ordering': ['category', 'order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='areahazardmap',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='areahazardmap',
            name='area',
        ),
        migrations.RemoveField(
            model_name='areahazardmap',
            name='hazard_indicator',
        ),
        migrations.AlterUniqueTogether(
            name='hazardlevel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='hazardlevel',
            name='hazard_indicator',
        ),
        migrations.RemoveField(
            model_name='instructionblock',
            name='sop',
        ),
        migrations.RemoveField(
            model_name='instructionstep',
            name='instruction_block',
        ),
        migrations.RemoveField(
            model_name='riskrule',
            name='area',
        ),
        migrations.RemoveField(
            model_name='riskrule',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='riskrule',
            name='scenario',
        ),
        migrations.AlterUniqueTogether(
            name='scenario',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='hazard_type',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='site_type',
        ),
        migrations.AlterUniqueTogether(
            name='sop',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sop',
            name='area',
        ),
        migrations.RemoveField(
            model_name='sop',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='sop',
            name='scenario',
        ),
        migrations.AlterModelOptions(
            name='risklevel',
            options={'ordering': ['severity'], 'verbose_name': 'Risk Level', 'verbose_name_plural': 'Risk Levels'},
        ),
        migrations.AddField(
            model_name='risklevel',
            name='color',
            field=models.CharField(blank=True, help_text="CSS color (e.g., 'red', '#FF0000')", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='risklevel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risklevel',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this risk level', null=True),
        ),
        migrations.AddField(
            model_name='risklevel',
            name='display_name',
            field=models.CharField(default='', help_text="Display name (e.g., 'Critical', 'High Risk')", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risklevel',
            name='icon',
            field=models.CharField(default='', help_text="Emoji icon (e.g., '🚨', '🟠')", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risklevel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this risk level is active'),
        ),
        migrations.AddField(
            model_name='risklevel',
            name='severity',
            field=models.PositiveIntegerField(default=0, help_text='Severity order (1=highest, 4=lowest)'),
        ),
        migrations.AddField(
            model_name='risklevel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='risklevel',
            name='name',
            field=models.CharField(help_text="Internal name (e.g., 'critical', 'high')", max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='risklevel',
            table='risk_levels',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='AreaHazardMap',
        ),
        migrations.DeleteModel(
            name='HazardIndicator',
        ),
        migrations.DeleteModel(
            name='HazardLevel',
        ),
        migrations.DeleteModel(
            name='HazardType',
        ),
        migrations.DeleteModel(
            name='InstructionBlock',
        ),
        migrations.DeleteModel(
            name='InstructionStep',
        ),
        migrations.DeleteModel(
            name='RiskRule',
        ),
        migrations.DeleteModel(
            name='Scenario',
        ),
        migrations.DeleteModel(
            name='SiteType',
        ),
        migrations.DeleteModel(
            name='SOP',
        ),
        migrations.AddField(
            model_name='fireresponse',
            name='risk_level',
            field=models.ForeignKey(blank=True, help_text='Optional risk level', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='bot.risklevel'),
        ),
        migrations.AddField(
            model_name='fireresponse',
            name='sub_category',
            field=models.ForeignKey(blank=True, help_text='Optional sub-category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='bot.subcategory'),
        ),
        migrations.AddIndex(
            model_name='fireresponse',
            index=models.Index(fields=['response_key'], name='fire_respon_respons_969117_idx'),
        ),
        migrations.AddIndex(
            model_name='fireresponse',
            index=models.Index(fields=['category', 'sub_category', 'risk_level'], name='fire_respon_categor_2b01a2_idx'),
        ),
        migrations.AddIndex(
            model_name='fireresponse',
            index=models.Index(fields=['is_active'], name='fire_respon_is_acti_a65f43_idx'),
        ),
    ]
