# Generated by Django 4.2 on 2026-01-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_firecategory_fireresponse_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='Unique identifier for the user', max_length=100)),
                ('submission_time', models.DateTimeField(auto_now_add=True, help_text='Time of submission')),
                ('location', models.CharField(help_text='Location of the incident', max_length=255)),
                ('description', models.TextField(help_text='Description of the incident')),
                ('site_tyep', models.CharField(help_text='Type of site (e.g., House, Building)', max_length=50)),
                ('site_location', models.CharField(help_text='Specific location within the site', max_length=255)),
                ('risk_level', models.CharField(help_text='Severity level of the incident', max_length=50)),
            ],
            options={
                'verbose_name': 'User Submission',
                'verbose_name_plural': 'User Submissions',
                'db_table': 'user_submissions',
                'ordering': ['-submission_time'],
            },
        ),
    ]
