# Generated by Django 4.2 on 2026-01-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_usersubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmission',
            name='location',
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='latitude',
            field=models.FloatField(help_text='Latitude of the incident location', null=True),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='longitude',
            field=models.FloatField(help_text='Longitude of the incident location', null=True),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the incident', null=True),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='risk_level',
            field=models.CharField(help_text='Severity level of the incident', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='site_location',
            field=models.CharField(help_text='Specific location within the site', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='site_tyep',
            field=models.CharField(help_text='Type of site (e.g., House, Building)', max_length=50, null=True),
        ),
    ]
