# Generated by Django 4.2 on 2026-01-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_remove_usersubmission_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='resplved_address',
            field=models.CharField(blank=True, help_text='Resolved address from coordinates', max_length=255, null=True),
        ),
    ]
