# Generated by Django 4.2 on 2026-01-25 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_usersubmission_resplved_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubmission',
            old_name='resplved_address',
            new_name='resolved_address',
        ),
    ]
