# Generated by Django 4.2 on 2026-01-25 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_rename_resplved_address_usersubmission_resolved_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubmission',
            old_name='site_tyep',
            new_name='site_type',
        ),
    ]
