# Generated by Django 4.2 on 2026-01-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_rename_site_tyep_usersubmission_site_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='user_id',
            field=models.CharField(help_text='Unique identifier for the user', max_length=100, unique=True),
        ),
    ]
